# src/strategies/signals.py

"""
Defines the data structures and validation mechanisms for trading signals.

This module provides a standardized, immutable `Signal` dataclass to represent
trading intentions generated by strategies. It ensures that all signals across
the framework are consistent, type-safe, and carry all necessary information
for execution, analysis, and reporting.

The use of enums for types and directions prevents common errors associated with
string literals and enhances code readability.
"""

import datetime
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, Optional, List

from src.core.exceptions import SignalError


class SignalDirection(str, Enum):
    """Enumerates the possible directions of a trading signal."""
    LONG = "LONG"
    SHORT = "SHORT"


class SignalType(str, Enum):
    """Enumerates the types of signals, indicating entry or exit."""
    ENTRY = "ENTRY"
    EXIT = "EXIT"


@dataclass(frozen=True)
class Signal:
    """
    An immutable data structure representing a trading signal.

    A signal is a pure, stateless representation of a strategy's decision at a
    specific point in time. It is not an order itself but contains all the
    necessary information to be converted into one by the execution engine.

    Attributes:
        strategy_name (str): The name of the strategy that generated the signal.
        timestamp (datetime.datetime): The timestamp of the data point that
                                     triggered the signal.
        direction (SignalDirection): The direction of the trade (LONG or SHORT).
        signal_type (SignalType): The type of signal (ENTRY or EXIT).
        symbol (str): The symbol of the asset to be traded (e.g., 'BTC/USDT').
        price (Optional[float]): The target price for the action. If None, it
                                 may imply a market order.
        stop_loss (Optional[float]): The suggested stop-loss price level.
        take_profit (Optional[float]): The suggested take-profit price level.
        confidence (float): A score between 0.0 and 1.0 indicating the
                            strategy's confidence in the signal. Defaults to 1.0.
        metadata (Dict[str, Any]): A dictionary for storing extra information,
                                   such as the indicator values that triggered
                                   the signal. Defaults to an empty dict.
    """
    strategy_name: str
    timestamp: datetime.datetime
    direction: SignalDirection
    signal_type: SignalType
    symbol: str
    price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    confidence: float = 1.0
    metadata: Dict[str, Any] = field(default_factory=dict, hash=False)

    def __post_init__(self):
        """
        Performs validation after the object has been initialized.
        """
        SignalValidator.validate(self)


class SignalValidator:
    """
    A dedicated class for validating the business logic of a Signal.
    """
    @staticmethod
    def validate(signal: 'Signal') -> None:
        """
        Validates the integrity and business rules of a Signal instance.

        Raises:
            SignalError: If any validation rule is violated.
        """
        validators: List = [
            SignalValidator._validate_confidence,
            SignalValidator._validate_prices,
            SignalValidator._validate_sl_tp_logic
        ]
        for validator_func in validators:
            validator_func(signal)

    @staticmethod
    def _validate_confidence(signal: 'Signal') -> None:
        """Checks if confidence is within the valid range [0.0, 1.0]."""
        if not (0.0 <= signal.confidence <= 1.0):
            raise SignalError(
                "Signal confidence must be between 0.0 and 1.0.",
                context={
                    "strategy": signal.strategy_name,
                    "confidence": signal.confidence
                }
            )

    @staticmethod
    def _validate_prices(signal: 'Signal') -> None:
        """Checks if price-related fields are positive if they are not None."""
        for price_field in ['price', 'stop_loss', 'take_profit']:
            price_value = getattr(signal, price_field)
            if price_value is not None and price_value <= 0:
                raise SignalError(
                    f"Signal '{price_field}' must be a positive value.",
                    context={
                        "strategy": signal.strategy_name,
                        price_field: price_value
                    }
                )

    @staticmethod
    def _validate_sl_tp_logic(signal: 'Signal') -> None:
        """
        Validates the logical consistency of stop-loss and take-profit levels
        relative to the entry price.
        """
        if signal.price is None:
            return  # Cannot validate SL/TP without a reference price

        # Validate Stop-Loss
        if signal.stop_loss is not None:
            if signal.direction == SignalDirection.LONG and signal.stop_loss >= signal.price:
                raise SignalError(
                    "Stop-loss for a LONG signal must be below the entry price.",
                    context={"price": signal.price, "stop_loss": signal.stop_loss}
                )
            if signal.direction == SignalDirection.SHORT and signal.stop_loss <= signal.price:
                raise SignalError(
                    "Stop-loss for a SHORT signal must be above the entry price.",
                    context={"price": signal.price, "stop_loss": signal.stop_loss}
                )

        # Validate Take-Profit
        if signal.take_profit is not None:
            if signal.direction == SignalDirection.LONG and signal.take_profit <= signal.price:
                raise SignalError(
                    "Take-profit for a LONG signal must be above the entry price.",
                    context={"price": signal.price, "take_profit": signal.take_profit}
                )
            if signal.direction == SignalDirection.SHORT and signal.take_profit >= signal.price:
                raise SignalError(
                    "Take-profit for a SHORT signal must be below the entry price.",
                    context={"price": signal.price, "take_profit": signal.take_profit}
                )
