"""create_initial_project_tables

Revision ID: 9cfc34e0bd4f
Revises: 
Create Date: 2025-05-31 09:57:57.597416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cfc34e0bd4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klines_1m',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique kline identifier (primary, auto-incremented).'),
    sa.Column('pair', sa.String(length=30), nullable=False, comment='Trading pair (e.g., BTCUSDC). Increased length for flexibility.'),
    sa.Column('kline_open_time', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='Kline open time (UTC, start of the interval).'),
    sa.Column('kline_close_time', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='Kline close time (UTC, end of the interval).'),
    sa.Column('open_price', sa.Numeric(precision=30, scale=15), nullable=False, comment='Kline open price. Increased precision.'),
    sa.Column('high_price', sa.Numeric(precision=30, scale=15), nullable=False, comment='Highest price during the kline period.'),
    sa.Column('low_price', sa.Numeric(precision=30, scale=15), nullable=False, comment='Lowest price during the kline period.'),
    sa.Column('close_price', sa.Numeric(precision=30, scale=15), nullable=False, comment='Kline close price.'),
    sa.Column('base_asset_volume', sa.Numeric(precision=30, scale=15), nullable=False, comment='Volume of the base asset (e.g., BTC for BTCUSDC) traded during the kline.'),
    sa.Column('quote_asset_volume', sa.Numeric(precision=30, scale=15), nullable=False, comment='Volume of the quote asset (e.g., USDC for BTCUSDC) traded during the kline.'),
    sa.Column('number_of_trades', sa.Integer(), nullable=False, comment='Total number of trades executed during the kline period.'),
    sa.Column('taker_buy_base_asset_volume', sa.Numeric(precision=30, scale=15), nullable=False, comment='Volume of the base asset bought by takers (market orders).'),
    sa.Column('taker_buy_quote_asset_volume', sa.Numeric(precision=30, scale=15), nullable=False, comment='Volume of the quote asset bought by takers.'),
    sa.Column('is_kline_closed', sa.Boolean(), nullable=False, comment='Boolean indicating if the kline is closed (TRUE) or still in formation (FALSE).'),
    sa.Column('db_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment="Timestamp of the record's creation in the database."),
    sa.Column('db_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment="Timestamp of the record's last update (auto-updated by trigger)."),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair', 'kline_open_time', name='uq_klines_1m_pair_open_time')
    )
    with op.batch_alter_table('klines_1m', schema=None) as batch_op:
        batch_op.create_index('idx_klines_1m_is_kline_closed', ['is_kline_closed'], unique=False, postgresql_where=sa.text('is_kline_closed = FALSE'))
        batch_op.create_index('idx_klines_1m_open_time_desc', [sa.literal_column('kline_open_time DESC')], unique=False)
        batch_op.create_index('idx_klines_1m_pair_open_time_desc', ['pair', sa.literal_column('kline_open_time DESC')], unique=False)

    op.create_table('strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_code', sa.String(length=100), nullable=False, comment='Unique human-readable code for the strategy (e.g., SMA_CROSS_V1).'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Descriptive name (e.g., Simple Moving Average Crossover Strategy).'),
    sa.Column('description', sa.String(), nullable=True, comment="Detailed description of the strategy's logic."),
    sa.Column('class_name', sa.String(length=255), nullable=False, comment='Python class name implementing the strategy (e.g., SMACrossStrategy).'),
    sa.Column('default_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Default configuration/parameters for the strategy in JSON format.'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='Version of the strategy definition.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='Whether the strategy is currently active for use.'),
    sa.Column('db_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('db_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_strategy_code'), ['strategy_code'], unique=True)

    op.create_table('backtest_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Strategy parameters used for this backtest.'),
    sa.Column('report_name', sa.String(length=255), nullable=True, comment='Optional custom name for the backtest report.'),
    sa.Column('pair', sa.String(length=30), nullable=False),
    sa.Column('kline_interval', sa.String(length=10), nullable=False, comment='Kline interval used (e.g., 1m, 1h).'),
    sa.Column('period_start_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_end_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=30, scale=15), nullable=True),
    sa.Column('final_capital', sa.Numeric(precision=30, scale=15), nullable=True),
    sa.Column('total_return_pct', sa.Numeric(precision=10, scale=4), nullable=True, comment='Total return in percentage.'),
    sa.Column('metrics_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Summary of key performance metrics (Sharpe, Sortino, Max Drawdown, etc.).'),
    sa.Column('backtest_engine_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Backtest engine configuration (fees, slippage).'),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_reports', schema=None) as batch_op:
        batch_op.create_index('idx_backtest_reports_strategy_pair_interval', ['strategy_id', 'pair', 'kline_interval'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_reports_pair'), ['pair'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_reports_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('live_trades_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Internal unique trade identifier.'),
    sa.Column('binance_order_id', sa.String(length=255), nullable=False, comment='Order ID from Binance.'),
    sa.Column('binance_client_order_id', sa.String(length=255), nullable=True, comment='Client Order ID sent to Binance.'),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('parameters_json_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot of strategy parameters at the time of the trade.'),
    sa.Column('pair', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False, comment='Trade side (e.g., BUY, SELL).'),
    sa.Column('order_type', sa.String(length=20), nullable=False, comment='Order type (e.g., LIMIT, MARKET).'),
    sa.Column('order_status', sa.String(length=50), nullable=False, comment='Final order status (e.g., FILLED, CANCELED).'),
    sa.Column('quantity_ordered', sa.Numeric(precision=30, scale=15), nullable=False),
    sa.Column('quantity_filled', sa.Numeric(precision=30, scale=15), nullable=False),
    sa.Column('price_target', sa.Numeric(precision=30, scale=15), nullable=True, comment='Target price for LIMIT orders.'),
    sa.Column('average_fill_price', sa.Numeric(precision=30, scale=15), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=30, scale=15), nullable=True),
    sa.Column('commission_asset', sa.String(length=10), nullable=True),
    sa.Column('transaction_time', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp of the trade execution on Binance.'),
    sa.Column('pnl_realized_quote', sa.Numeric(precision=30, scale=15), nullable=True, comment='Realized Profit or Loss in quote asset.'),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('db_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_uuid')
    )
    with op.batch_alter_table('live_trades_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_trades_log_binance_client_order_id'), ['binance_client_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_live_trades_log_binance_order_id'), ['binance_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_live_trades_log_pair'), ['pair'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_trades_log_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('optimization_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False, comment='Unique name for the optimization job/study.'),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=30), nullable=False),
    sa.Column('kline_interval', sa.String(length=10), nullable=False),
    sa.Column('optimization_type', sa.String(length=50), nullable=True, comment='Type of optimization (e.g., WFO, Optuna_TPE).'),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Optimization configuration (search space, WFO settings).'),
    sa.Column('optuna_study_name_internal', sa.String(length=255), nullable=True, comment='Internal Optuna study name, if applicable.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Job status (e.g., PENDING, RUNNING, COMPLETED, FAILED).'),
    sa.Column('best_trial_id_internal', sa.String(length=255), nullable=True),
    sa.Column('best_parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Best parameters found by the optimization.'),
    sa.Column('best_objective_value', sa.Numeric(), nullable=True, comment='Objective function value for the best parameters.'),
    sa.Column('job_start_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('job_end_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('db_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('db_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('optimization_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimization_jobs_job_name'), ['job_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_optimization_jobs_pair'), ['pair'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_jobs_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('strategy_parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('parameters_set_name', sa.String(length=255), nullable=False, comment='Named set of parameters (e.g., BTCUSDC_1h_Optimized_Q1_2024).'),
    sa.Column('parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='The actual parameters for this set in JSON format.'),
    sa.Column('source_description', sa.String(), nullable=True, comment='How this parameter set was obtained (e.g., Optuna WFO run X).'),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('db_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('db_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'parameters_set_name', name='uq_strategy_parameters_set_name')
    )
    with op.batch_alter_table('strategy_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_parameters_strategy_id'), ['strategy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_parameters_strategy_id'))

    op.drop_table('strategy_parameters')
    with op.batch_alter_table('optimization_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_optimization_jobs_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_optimization_jobs_pair'))
        batch_op.drop_index(batch_op.f('ix_optimization_jobs_job_name'))

    op.drop_table('optimization_jobs')
    with op.batch_alter_table('live_trades_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_trades_log_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_live_trades_log_pair'))
        batch_op.drop_index(batch_op.f('ix_live_trades_log_binance_order_id'))
        batch_op.drop_index(batch_op.f('ix_live_trades_log_binance_client_order_id'))

    op.drop_table('live_trades_log')
    with op.batch_alter_table('backtest_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_reports_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_reports_pair'))
        batch_op.drop_index('idx_backtest_reports_strategy_pair_interval')

    op.drop_table('backtest_reports')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_strategy_code'))

    op.drop_table('strategies')
    with op.batch_alter_table('klines_1m', schema=None) as batch_op:
        batch_op.drop_index('idx_klines_1m_pair_open_time_desc')
        batch_op.drop_index('idx_klines_1m_open_time_desc')
        batch_op.drop_index('idx_klines_1m_is_kline_closed', postgresql_where=sa.text('is_kline_closed = FALSE'))

    op.drop_table('klines_1m')
    # ### end Alembic commands ###
